baseURL = 'http://bartverhavert.be'
languageCode = 'en-us'
title = 'Bart Verhavert'
theme = 'hugo-coder'

contentDir = 'content'

[params]
  author = "Bart Verhavert"
  info = "freelance iOS developer"
  gravatar = "hello@bartverhavert.be"
  keywords = "freelance,iOS,developer,personal"
  colorScheme = "dark"
  hidecolorschemetoggle = true

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 1
  url = "https://twitter.com/bartverhavert"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/bartverhavert/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/bartverhavert/"
